<?php
defined('MOODLE_INTERNAL') || die();
$active=0;$upcoming=0;$completed=0;$now=time();foreach($sessions as $s){if($s->status==='open')$active++;elseif($s->status==='closed')$completed++;else$upcoming++;}
echo $OUTPUT->header();echo '<div class="wsg-v12-dashboard"><div class="wsg-dashboard-hero"><div><span class="wsg-v12-eyebrow">WORKSHEET GRADER V12</span><h2>Quản lý buổi học</h2><p>Tạo buổi, chọn phiếu, chia nhóm và mở cho học sinh theo một quy trình thống nhất.</p></div><a href="#wsg-create-session" class="btn btn-primary btn-lg">+ Tạo buổi mới</a></div>';
echo $OUTPUT->render(worksheetgrader_nav_tabs($cm,'sessions'));if($saveerror!=='')echo $OUTPUT->notification(s($saveerror),'error');echo '<div class="wsg-dashboard-stats"><div class="wsg-stat-card"><span class="wsg-stat-icon is-live">●</span><div><strong>'.$active.'</strong><span>Đang diễn ra</span></div></div><div class="wsg-stat-card"><span class="wsg-stat-icon">◷</span><div><strong>'.$upcoming.'</strong><span>Sắp tới / Bản nháp</span></div></div><div class="wsg-stat-card"><span class="wsg-stat-icon is-done">✓</span><div><strong>'.$completed.'</strong><span>Đã kết thúc</span></div></div></div>';
echo '<div class="wsg-dashboard-section"><div class="wsg-section-title"><div><h3>Các buổi học</h3><p>Theo dõi trạng thái thiết lập và truy cập nhanh từng bước.</p></div></div><div class="wsg-session-cards">';
if(!$sessions)echo '<div class="wsg-empty-state"><div>📚</div><h3>Chưa có buổi học</h3><p>Tạo buổi đầu tiên rồi chọn phiếu từ Kho phiếu dùng chung.</p></div>';
foreach($sessions as $s){$has=worksheetgrader_session_has_content($s);$teams=$s->teammode==='individual'?'Cá nhân':$DB->count_records('wsg_team',['sessionid'=>$s->id]);$attempts=$DB->count_records_select('wsg_attempt','sessionid=? AND status IN (?,?)',[$s->id,'submitted','graded']);$statuslabel=$s->status==='open'?'Đang mở':($s->status==='closed'?'Đã kết thúc':'Bản nháp');$statusclass=$s->status==='open'?'is-open':($s->status==='closed'?'is-closed':'is-draft');echo '<article class="wsg-session-card"><div class="wsg-session-card-main"><div class="wsg-session-date"><strong>'.userdate($s->sessiondate,'%d').'</strong><span>'.userdate($s->sessiondate,'%m/%Y').'</span></div><div class="wsg-session-info"><div><span class="wsg-status '.$statusclass.'">'.$statuslabel.'</span><span class="wsg-kind-badge">'.s(strtoupper($s->worksheetkind??($s->contentmode??'html'))).'</span></div><h3>'.s($s->name).'</h3><p>'.userdate($s->sessiondate,get_string('strftimedatetimeshort')).'</p><div class="wsg-session-progress"><span class="'.($has?'is-ok':'').'">'.($has?'✓':'○').' Phiếu</span><span class="'.(($s->teammode==='individual'||$teams)?'is-ok':'').'">'.(($s->teammode==='individual'||$teams)?'✓':'○').' '.($s->teammode==='individual'?'Cá nhân':$teams.' nhóm').'</span><span>📄 '.$attempts.' bài nộp</span></div></div></div><div class="wsg-session-card-actions"><a class="btn btn-outline-primary" href="content.php?id='.$id.'&sessionid='.$s->id.'">Chọn phiếu</a><a class="btn btn-outline-primary" href="teams.php?id='.$id.'&sessionid='.$s->id.'">'.($s->teammode==='individual'?'Cá nhân':'Tạo nhóm').'</a>';if($s->status==='draft')echo '<a class="btn btn-primary" href="ready.php?id='.$id.'&sessionid='.$s->id.'">Kiểm tra & mở</a>';else echo '<a class="btn btn-primary" href="grade.php?id='.$id.'&sessionid='.$s->id.'">Chấm điểm</a>';echo '</div></article>';}
echo '</div></div><section id="wsg-create-session" class="wsg-create-session"><div class="wsg-create-copy"><span class="wsg-v12-eyebrow">BƯỚC 1/4</span><h2>Tạo buổi học mới</h2><p>Chỉ nhập thông tin tổ chức. Phiếu học tập và nhóm được thiết lập ở các bước tiếp theo, nên thao tác này không phụ thuộc ONLYOFFICE.</p><div class="wsg-create-points"><div><span>1</span><strong>Thông tin buổi</strong></div><div><span>2</span><strong>Chọn phiếu</strong></div><div><span>3</span><strong>Tạo nhóm</strong></div><div><span>4</span><strong>Xác nhận & mở</strong></div></div></div><div class="wsg-create-form card"><div class="card-body">';$form->display();echo '</div></div></section></div>';echo $OUTPUT->footer();
