<?php
defined('MOODLE_INTERNAL') || die();
require_capability('mod/worksheetgrader:manageteams',$context);
if(($session->teammode??'temporary')==='individual'){
 echo $OUTPUT->header();echo html_writer::div('<span class="wsg-v12-eyebrow">BƯỚC 3/4</span><h2>Chế độ cá nhân</h2><p>Buổi này không cần chia nhóm. Mỗi học sinh sẽ có bài làm riêng khi mở buổi.</p>','wsg-v12-pagehead');echo $OUTPUT->render(worksheetgrader_nav_tabs($cm,'teams',$sessionid));echo html_writer::div('<div class="wsg-ready-card is-ok"><span>✓</span><div><strong>Không cần tạo nhóm</strong><p>Hệ thống sẽ tạo workspace cá nhân khi học sinh bắt đầu.</p></div></div>','wsg-ready-grid');echo html_writer::link(new moodle_url('/mod/worksheetgrader/ready.php',['id'=>$id,'sessionid'=>$sessionid]),'Tiếp tục: Xác nhận & mở buổi →',['class'=>'btn btn-primary btn-lg']);echo $OUTPUT->footer();return;
}
$error='';
if(data_submitted() && confirm_sesskey()){
 try{$tool=optional_param('tool','',PARAM_ALPHA);if($tool==='moodlegroups'){\mod_worksheetgrader\service\team_manager::import_moodle_groups((int)$course->id,$sessionid,(int)$USER->id);}elseif($tool==='copy'){$sourceid=required_param('sourceid',PARAM_INT);\mod_worksheetgrader\service\session_manager::copy_teams($sourceid,$sessionid,(int)$USER->id);}redirect(new moodle_url('/mod/worksheetgrader/teams.php',['id'=>$id,'sessionid'=>$sessionid]));}catch(Throwable $e){$error=$e->getMessage();}
}
$students=worksheetgrader_get_students($context);$layout=\mod_worksheetgrader\service\team_manager::get_layout($sessionid);$assigned=[];foreach($layout as $t)foreach($t['members'] as $uid)$assigned[(int)$uid]=1;$previous=$DB->get_records_select('wsg_session','worksheetgraderid=? AND id<>? AND teammode<>? AND status IN (?,?)',[$activity->id,$sessionid,'individual','draft','open'],'sessiondate DESC','id,name');
$studentmap=[];foreach($students as $u)$studentmap[$u->id]=['id'=>(int)$u->id,'name'=>fullname($u),'email'=>$u->email??''];
$PAGE->requires->js_call_amd('mod_worksheetgrader/team_builder_v12','init',[['sessionid'=>$sessionid,'students'=>array_values($studentmap),'layout'=>$layout]]);
echo $OUTPUT->header();echo html_writer::div('<span class="wsg-v12-eyebrow">BƯỚC 3/4</span><h2>Tạo nhóm học sinh</h2><p>Kéo thả học sinh giữa các nhóm, tự chia đều hoặc nhập nhanh từ Moodle Groups.</p>','wsg-v12-pagehead');echo $OUTPUT->render(worksheetgrader_nav_tabs($cm,'teams',$sessionid));
if($error!=='')echo $OUTPUT->notification(s($error),'error');
echo '<div class="wsg-v12-steps"><div class="wsg-v12-step is-done"><span>✓</span><strong>Thông tin buổi</strong></div><div class="wsg-v12-step is-done"><span>✓</span><strong>Chọn phiếu</strong></div><div class="wsg-v12-step is-active"><span>3</span><strong>Tạo nhóm</strong></div><div class="wsg-v12-step"><span>4</span><strong>Xác nhận & mở</strong></div></div>';
echo '<div class="wsg-team-toolbar"><div><button class="btn btn-primary" type="button" data-action="auto-balance">⚡ Tự chia đều</button> <button class="btn btn-outline-primary" type="button" data-action="add-team">+ Thêm nhóm</button></div><div class="wsg-team-toolbar-secondary"><form method="post" class="d-inline"><input type="hidden" name="sesskey" value="'.sesskey().'"><input type="hidden" name="tool" value="moodlegroups"><button class="btn btn-outline-secondary">Lấy Moodle Groups</button></form>';if($previous){echo '<form method="post" class="d-inline"><input type="hidden" name="sesskey" value="'.sesskey().'"><input type="hidden" name="tool" value="copy"><select name="sourceid" class="form-select d-inline-block w-auto">';foreach($previous as $p)echo '<option value="'.$p->id.'">'.s($p->name).'</option>';echo '</select> <button class="btn btn-outline-secondary">Sao chép buổi trước</button></form>';}echo '</div></div>';
echo '<div class="wsg-teamstudio"><aside class="wsg-unassigned"><div class="wsg-team-panel-title"><div><strong>Học sinh chưa xếp nhóm</strong><small data-region="unassigned-count">'.(count($students)-count($assigned)).' học sinh</small></div></div><input class="form-control mb-3" placeholder="Tìm học sinh…" data-action="student-search"><div class="wsg-student-pool" data-region="unassigned" data-dropzone="1">';foreach($students as $u){if(isset($assigned[$u->id]))continue;echo '<div class="wsg-student-chip" draggable="true" data-userid="'.$u->id.'"><span class="wsg-avatar">'.s(mb_substr($u->firstname,0,1).mb_substr($u->lastname,0,1)).'</span><span><strong>'.s(fullname($u)).'</strong><small>'.s($u->email??'').'</small></span><span class="wsg-drag">⋮⋮</span></div>';}echo '</div></aside><main class="wsg-teams-canvas" data-region="teams">';foreach($layout as $index=>$team){echo '<section class="wsg-team-card" data-teamid="'.(int)$team['id'].'"><div class="wsg-team-card-head"><input class="form-control wsg-team-name" value="'.s($team['name']).'" aria-label="Tên nhóm"><span class="badge bg-light text-dark" data-region="team-count">'.count($team['members']).' thành viên</span><button type="button" class="btn btn-sm btn-link text-danger" data-action="remove-team">×</button></div><div class="wsg-team-dropzone" data-dropzone="1">';foreach($team['members'] as $uid){$u=$studentmap[$uid]??['name'=>'User #'.$uid,'email'=>''];echo '<div class="wsg-student-chip" draggable="true" data-userid="'.$uid.'"><span class="wsg-avatar">'.s(mb_substr($u['name'],0,2)).'</span><span><strong>'.s($u['name']).'</strong><small>'.s($u['email']).'</small></span><span class="wsg-drag">⋮⋮</span></div>';}echo '</div></section>';}echo '</main></div>';
echo '<div class="wsg-team-savebar"><div><strong data-region="save-status">Chưa có thay đổi</strong><small>Hệ thống lưu ID nhóm thật và cập nhật tại chỗ, không tải lại trang.</small></div><div><button class="btn btn-success btn-lg" type="button" data-action="save-layout">Lưu nhóm</button> <a class="btn btn-primary btn-lg" href="'.(new moodle_url('/mod/worksheetgrader/ready.php',['id'=>$id,'sessionid'=>$sessionid]))->out().'">Tiếp tục →</a></div></div>';
echo $OUTPUT->footer();
