<?php
require_once('../../config.php');
require_once(__DIR__ . '/lib.php');
use local_coursepublisher\form\discovery_rule_form;
use local_coursepublisher\form\discovery_container_form;
use local_coursepublisher\local\service;
require_login();
$context=context_system::instance();
require_capability('local/coursepublisher:configureprograms',$context);
$PAGE->set_context($context); $PAGE->set_url(new moodle_url('/local/coursepublisher/discovery_rules.php')); $PAGE->set_title(get_string('nav_discoveryrules','local_coursepublisher')); $PAGE->set_heading(get_string('pluginname','local_coursepublisher'));
$editrule=optional_param('editrule',0,PARAM_INT); $editcontainer=optional_param('editcontainer',0,PARAM_INT); $togglerule=optional_param('togglerule',0,PARAM_INT); $togglecontainer=optional_param('togglecontainer',0,PARAM_INT); $error=null;
try {
    if ($togglerule) { require_sesskey(); service::toggle('local_cp_discovery_rule',$togglerule,'discovery_rule'); redirect($PAGE->url,get_string('toggled','local_coursepublisher')); }
    if ($togglecontainer) { require_sesskey(); service::toggle('local_cp_discovery_container',$togglecontainer,'discovery_container'); redirect($PAGE->url,get_string('toggled','local_coursepublisher')); }
} catch(Throwable $e){$error=$e->getMessage();}
$ruleform=new discovery_rule_form(); $containerform=new discovery_container_form();
if ($ruleform->is_cancelled() || $containerform->is_cancelled()) redirect($PAGE->url);
if ($data=$ruleform->get_data()) { if (($data->formkind??'')==='rule') { try{service::save_discovery_rule($data);redirect($PAGE->url,get_string('saved','local_coursepublisher'));}catch(Throwable $e){$error=$e->getMessage();} } }
if ($data=$containerform->get_data()) { if (($data->formkind??'')==='container') { try{service::save_discovery_container($data);redirect($PAGE->url,get_string('saved','local_coursepublisher'));}catch(Throwable $e){$error=$e->getMessage();} } }
if($editrule)$ruleform->set_data($DB->get_record('local_cp_discovery_rule',['id'=>$editrule],'*',MUST_EXIST));
if($editcontainer)$containerform->set_data($DB->get_record('local_cp_discovery_container',['id'=>$editcontainer],'*',MUST_EXIST));
local_coursepublisher_output_start('discoveryrules',get_string('nav_discoveryrules','local_coursepublisher'),get_string('discoveryrulessubtitle','local_coursepublisher'));
if($error)echo html_writer::div(s($error),'cp-notice-error');
local_coursepublisher_card_start($editrule?get_string('editdiscoveryrule','local_coursepublisher'):get_string('newdiscoveryrule','local_coursepublisher'),get_string('discoveryrulehint','local_coursepublisher'),'cp-form-card'); $ruleform->display(); local_coursepublisher_card_end();
$sql="SELECT r.*, g.groupkey, g.name AS groupname, p.name AS programname FROM {local_cp_discovery_rule} r JOIN {local_cp_target_group} g ON g.id=r.targetgroupid JOIN {local_cp_program} p ON p.id=g.programid ORDER BY p.name,g.sortorder,r.priority DESC,r.sortorder,r.name"; $rules=$DB->get_records_sql($sql);
local_coursepublisher_card_start(get_string('discoveryrulelist','local_coursepublisher'),get_string('recordcount','local_coursepublisher',count($rules)));
if(!$rules){echo html_writer::div(get_string('discoveryruleempty','local_coursepublisher'),'cp-empty');}else{$t=new html_table();$t->attributes['class']='generaltable cp-table';$t->head=[get_string('targetgroupgrade','local_coursepublisher'),get_string('rulename','local_coursepublisher'),get_string('rulefield','local_coursepublisher'),get_string('matchtype','local_coursepublisher'),get_string('pattern','local_coursepublisher'),get_string('status','local_coursepublisher'),get_string('actions','local_coursepublisher')];foreach($rules as $r){$edit=html_writer::link(new moodle_url($PAGE->url,['editrule'=>$r->id]),get_string('edit','local_coursepublisher'),['class'=>'btn btn-sm btn-outline-secondary']);$toggle=html_writer::link(new moodle_url($PAGE->url,['togglerule'=>$r->id,'sesskey'=>sesskey()]),$r->enabled?get_string('disable','local_coursepublisher'):get_string('enable','local_coursepublisher'),['class'=>'btn btn-sm btn-outline-secondary']);$t->data[]=[format_string($r->programname).' / '.format_string($r->groupname).' ['.s($r->groupkey).']',format_string($r->name),s($r->fieldname),s($r->matchtype),html_writer::span(s($r->pattern),'cp-code'),local_coursepublisher_badge($r->enabled?'enabled':'disabled'),html_writer::div($edit.$toggle,'cp-actions')];}echo html_writer::div(html_writer::table($t),'cp-table-wrap');} local_coursepublisher_card_end();
local_coursepublisher_card_start($editcontainer?get_string('editcontainerrule','local_coursepublisher'):get_string('newcontainerrule','local_coursepublisher'),get_string('containerrulehint','local_coursepublisher'),'cp-form-card'); $containerform->display(); local_coursepublisher_card_end();
$containers=$DB->get_records('local_cp_discovery_container',null,'sortorder,name');local_coursepublisher_card_start(get_string('containerrulelist','local_coursepublisher'),get_string('recordcount','local_coursepublisher',count($containers)));if(!$containers){echo html_writer::div(get_string('containerruleempty','local_coursepublisher'),'cp-empty');}else{$t=new html_table();$t->attributes['class']='generaltable cp-table';$t->head=[get_string('containerrulename','local_coursepublisher'),get_string('matchtype','local_coursepublisher'),get_string('pattern','local_coursepublisher'),get_string('status','local_coursepublisher'),get_string('actions','local_coursepublisher')];foreach($containers as $r){$edit=html_writer::link(new moodle_url($PAGE->url,['editcontainer'=>$r->id]),get_string('edit','local_coursepublisher'),['class'=>'btn btn-sm btn-outline-secondary']);$toggle=html_writer::link(new moodle_url($PAGE->url,['togglecontainer'=>$r->id,'sesskey'=>sesskey()]),$r->enabled?get_string('disable','local_coursepublisher'):get_string('enable','local_coursepublisher'),['class'=>'btn btn-sm btn-outline-secondary']);$t->data[]=[format_string($r->name),s($r->matchtype),html_writer::span(s($r->pattern),'cp-code'),local_coursepublisher_badge($r->enabled?'enabled':'disabled'),html_writer::div($edit.$toggle,'cp-actions')];}echo html_writer::div(html_writer::table($t),'cp-table-wrap');}local_coursepublisher_card_end();local_coursepublisher_output_end();
