<?php
// This file is part of Moodle - http://moodle.org/.

namespace mod_worksheetgrader\docspace;

defined('MOODLE_INTERNAL') || die();

/**
 * Small server-side client for ONLYOFFICE DocSpace Cloud.
 *
 * The administrator API key never reaches browser-side JavaScript. Student
 * frames only receive a room-scoped public request token generated by DocSpace.
 */
final class client {
    /** @var string */
    private string $baseurl;
    /** @var string */
    private string $apikey;
    /** @var int */
    private int $timeout;

    public function __construct(?string $baseurl = null, ?string $apikey = null, ?int $timeout = null) {
        $this->baseurl = rtrim((string)($baseurl ?? get_config('mod_worksheetgrader', 'docspaceurl')), '/');
        $this->apikey = trim((string)($apikey ?? get_config('mod_worksheetgrader', 'docspaceapikey')));
        $this->timeout = max(10, (int)($timeout ?? get_config('mod_worksheetgrader', 'docspacetimeout') ?: 60));
        if ($this->baseurl === '' || $this->apikey === '') {
            throw new \moodle_exception('docspacenotconfigured', 'mod_worksheetgrader');
        }
        if (!preg_match('~^https://~i', $this->baseurl)) {
            throw new \moodle_exception('docspacehttpsrequired', 'mod_worksheetgrader');
        }
    }

    public function get_base_url(): string {
        return $this->baseurl;
    }

    /** Check credentials and return a compact response. */
    public function test_connection(): array {
        return $this->request_json('GET', '/api/2.0/files/rooms', null, ['count' => 1]);
    }

    /** Create one anonymous Public Room workspace. */
    public function create_public_room(string $title): array {
        $result = $this->request_json('POST', '/api/2.0/files/rooms', [
            'title' => $title,
            'roomType' => 'PublicRoom',
            'quota' => null,
            'indexing' => false,
            'denyDownload' => false,
            'private' => false,
        ]);
        $roomid = self::find_scalar($result, ['id', 'roomId', 'roomid']);
        if ($roomid === null || $roomid === '') {
            throw new \moodle_exception('docspaceinvalidresponse', 'mod_worksheetgrader', '', 'room id');
        }
        return ['id' => (string)$roomid, 'raw' => $result];
    }

    /** Create or refresh an anonymous Public Room link. Access 2 edits; access 1 reads. */
    public function set_room_link(string $roomid, int $access = 2): array {
        $result = $this->request_json('PUT', '/api/2.0/files/rooms/' . rawurlencode($roomid) . '/links', [
            'access' => $access,
            'expirationDate' => null,
            'internal' => false,
            'primary' => true,
        ]);
        try {
            return $this->normalise_link($result);
        } catch (\Throwable $exception) {
            return $this->get_primary_room_link($roomid);
        }
    }

    /** Return the primary external link for a Public Room. */
    public function get_primary_room_link(string $roomid): array {
        $result = $this->request_json('GET', '/api/2.0/files/rooms/' . rawurlencode($roomid) . '/link');
        return $this->normalise_link($result);
    }

    /** Return all external/invitation links for a Public Room. */
    public function get_room_links(string $roomid): array {
        $result = $this->request_json('GET', '/api/2.0/files/rooms/' . rawurlencode($roomid) . '/links');
        return $this->normalise_link($result);
    }

    /** Remove a dedicated DocSpace room. */
    public function delete_room(string $roomid): array {
        return $this->request_json('DELETE', '/api/2.0/files/rooms/' . rawurlencode($roomid));
    }

    /** Create an isolated folder inside a room or parent folder. */
    public function create_folder(string $parentfolderid, string $title): array {
        $result = $this->request_json('POST', '/api/2.0/files/folder/' . rawurlencode($parentfolderid), [
            'title' => $title,
        ]);
        $id = self::find_scalar($result, ['id', 'folderId', 'folderid']);
        if ($id === null || $id === '') {
            throw new \moodle_exception('docspaceinvalidresponse', 'mod_worksheetgrader', '', 'folder id');
        }
        $name = self::find_scalar($result, ['title', 'name']) ?: $title;
        return ['id' => (string)$id, 'title' => (string)$name, 'raw' => $result];
    }

    /** Create a blank document in a room. */
    public function create_file(string $folderid, string $filename): array {
        $result = $this->request_json('POST', '/api/2.0/files/' . rawurlencode($folderid) . '/file', [
            'title' => $filename,
        ]);
        return $this->normalise_file($result, $filename);
    }

    /** Upload a local file to a room using multipart/form-data. */
    public function upload_file(string $folderid, string $localpath, string $filename, string $mimetype): array {
        if (!is_readable($localpath)) {
            throw new \moodle_exception('filenotfound');
        }
        $curl = $this->new_curl(false);
        $payload = [
            'file' => new \CURLFile($localpath, $mimetype ?: 'application/octet-stream', $filename),
            'createNewIfExist' => 'true',
            'storeOriginalFileFlag' => 'true',
        ];
        $raw = $curl->post(
            $this->baseurl . '/api/2.0/files/' . rawurlencode($folderid) . '/upload',
            $payload,
            ['CURLOPT_TIMEOUT' => $this->timeout]
        );
        $result = $this->decode_response($curl, $raw);
        return $this->normalise_file($result, $filename);
    }

    /** Copy a template file into the shared activity room. */
    public function copy_file(string $fileid, string $destinationfolderid, string $filename): array {
        $result = $this->request_json('POST', '/api/2.0/files/file/' . rawurlencode($fileid) . '/copyas', [
            'destTitle' => $filename,
            'destFolderId' => ctype_digit($destinationfolderid) ? (int)$destinationfolderid : $destinationfolderid,
            'enableExternalExt' => true,
            'password' => null,
            'toForm' => false,
        ]);
        return $this->normalise_file($result, $filename);
    }

    /**
     * Create or update the primary external link for one file.
     * Access 2 is editable; access 1 is read-only.
     */
    public function set_file_link(string $fileid, int $access = 2): array {
        $current = null;
        try {
            $current = $this->get_primary_file_link($fileid);
        } catch (\Throwable $exception) {
            // A missing primary link is expected for a newly-created file.
            $current = null;
        }

        if ($current && !empty($current['id'])) {
            $this->request_json('PUT', '/api/2.0/files/file/' . rawurlencode($fileid) . '/links', [
                'sharedTo' => [
                    'id' => (string)$current['id'],
                    'access' => $access,
                    'isExpired' => false,
                    'expirationDate' => null,
                ],
            ]);
        } else {
            $result = $this->request_json('POST', '/api/2.0/files/file/' . rawurlencode($fileid) . '/link', [
                'access' => $access,
                'expirationDate' => null,
                'password' => null,
                'denyDownload' => false,
            ]);
            $created = $this->normalise_link($result);
            if (!empty($created['requesttoken'])) {
                return $created;
            }
        }

        return $this->get_primary_file_link($fileid);
    }

    /**
     * Create or update a folder-scoped external link.
     *
     * A folder token is required for anonymous editing of files in a Public
     * Room. File-scoped public tokens are suitable for viewing but can be
     * downgraded to a read-only editor by DocSpace Cloud.
     */
    public function set_folder_link(string $folderid, int $access = 2): array {
        $current = null;
        try {
            $current = $this->get_primary_folder_link($folderid);
        } catch (\Throwable $exception) {
            $current = null;
        }

        if ($current && !empty($current['id'])) {
            $this->request_json('PUT', '/api/2.0/files/folder/' . rawurlencode($folderid) . '/links', [
                'sharedTo' => [
                    'id' => (string)$current['id'],
                    'access' => $access,
                    'isExpired' => false,
                    'expirationDate' => null,
                ],
            ]);
        } else {
            $result = $this->request_json('POST', '/api/2.0/files/folder/' . rawurlencode($folderid) . '/link', [
                'access' => $access,
                'expirationDate' => null,
                'password' => null,
                'denyDownload' => false,
            ]);
            $created = $this->normalise_link($result);
            if (!empty($created['requesttoken'])) {
                return $created;
            }
        }

        return $this->get_primary_folder_link($folderid);
    }

    /** Return the primary external link for one isolated folder. */
    public function get_primary_folder_link(string $folderid): array {
        $result = $this->request_json('GET', '/api/2.0/files/folder/' . rawurlencode($folderid) . '/link');
        return $this->normalise_link($result);
    }

    /** Return all external links for one folder. */
    public function get_folder_links(string $folderid): array {
        $result = $this->request_json('GET', '/api/2.0/files/folder/' . rawurlencode($folderid) . '/links');
        return $this->normalise_link($result);
    }

    /** Return the primary external link for one file. */
    public function get_primary_file_link(string $fileid): array {
        $result = $this->request_json('GET', '/api/2.0/files/file/' . rawurlencode($fileid) . '/link');
        return $this->normalise_link($result);
    }

    /** Return all external file links, normalised to the primary link. */
    public function get_file_links(string $fileid): array {
        $result = $this->request_json('GET', '/api/2.0/files/file/' . rawurlencode($fileid) . '/links');
        return $this->normalise_link($result);
    }

    /** Return a temporary download URL for a DocSpace file. */
    public function get_presigned_uri(string $fileid): string {
        $result = $this->request_json('GET', '/api/2.0/files/file/' . rawurlencode($fileid) . '/presigneduri');
        $uri = self::find_scalar($result, ['url', 'uri', 'presignedUri', 'presigneduri']);
        if (!$uri || !is_string($uri)) {
            throw new \moodle_exception('docspaceinvalidresponse', 'mod_worksheetgrader', '', 'download url');
        }
        return $uri;
    }

    /** Download a remote file through Moodle's HTTP wrapper. */
    public function download_to_path(string $url, string $destination): void {
        if (!preg_match('~^https://~i', $url)) {
            throw new \moodle_exception('docspaceinvalidresponse', 'mod_worksheetgrader', '', 'insecure download URL');
        }
        $curl = new \curl();
        $raw = $curl->get($url, [], ['CURLOPT_TIMEOUT' => max(120, $this->timeout)]);
        $info = $curl->get_info();
        $code = (int)($info['http_code'] ?? 0);
        if ($code < 200 || $code >= 300 || !is_string($raw)) {
            throw new \moodle_exception('docspacehttp', 'mod_worksheetgrader', '', $code ?: 'download');
        }
        if (file_put_contents($destination, $raw) === false) {
            throw new \moodle_exception('cannotwritefile');
        }
    }

    private function normalise_file(array $result, string $fallbackname): array {
        $id = self::find_scalar($result, ['id', 'fileId', 'fileid']);
        if ($id === null || $id === '') {
            throw new \moodle_exception('docspaceinvalidresponse', 'mod_worksheetgrader', '', 'file id');
        }
        $title = self::find_scalar($result, ['title', 'fileName', 'filename', 'name']) ?: $fallbackname;
        return ['id' => (string)$id, 'title' => (string)$title, 'raw' => $result];
    }

    private function normalise_link(array $result): array {
        $link = self::find_link_object($result) ?: $result;
        $url = self::find_scalar($link, ['shareLink', 'sharedTo', 'webUrl', 'url', 'link']);
        $token = self::find_scalar($link, ['requestToken', 'requesttoken', 'token']);
        $id = self::find_scalar($link, ['id', 'linkId', 'linkid']);
        if (!$token && is_string($url)) {
            $query = parse_url(html_entity_decode($url), PHP_URL_QUERY);
            if ($query) {
                parse_str($query, $params);
                $token = $params['requestToken'] ?? $params['requesttoken'] ?? $params['token'] ?? null;
            }
        }
        if (!$token) {
            $token = self::find_token_like($result);
        }
        if (!$token) {
            throw new \moodle_exception('docspaceinvalidresponse', 'mod_worksheetgrader', '', 'public request token');
        }
        return [
            'id' => $id === null ? '' : (string)$id,
            'url' => is_string($url) ? $url : '',
            'requesttoken' => (string)$token,
            'raw' => $result,
        ];
    }

    /** Locate a sharedLink-shaped object without accidentally selecting a file/room ID. */
    private static function find_link_object(array $data): ?array {
        $lowerkeys = array_map('strtolower', array_keys($data));
        $hasrequesttoken = in_array('requesttoken', $lowerkeys, true);
        $hassharelink = in_array('sharelink', $lowerkeys, true);
        if ($hasrequesttoken || $hassharelink) {
            return $data;
        }
        foreach ($data as $key => $value) {
            if (is_array($value) && strtolower((string)$key) === 'sharedlink') {
                return $value;
            }
        }
        foreach ($data as $value) {
            if (is_array($value)) {
                $found = self::find_link_object($value);
                if ($found) {
                    return $found;
                }
            }
        }
        return null;
    }

    private function request_json(string $method, string $path, ?array $body = null, array $query = []): array {
        $url = $this->baseurl . $path;
        if ($query) {
            $url .= '?' . http_build_query($query, '', '&', PHP_QUERY_RFC3986);
        }
        $curl = $this->new_curl(true);
        $options = ['CURLOPT_TIMEOUT' => $this->timeout];
        $payload = $body === null ? '' : json_encode($body, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
        switch (strtoupper($method)) {
            case 'GET':
                $raw = $curl->get($url, [], $options);
                break;
            case 'POST':
                $raw = $curl->post($url, $payload, $options);
                break;
            case 'PUT':
                $raw = $curl->put($url, $payload, $options);
                break;
            case 'DELETE':
                $raw = $curl->delete($url, $payload, $options);
                break;
            default:
                throw new \coding_exception('Unsupported DocSpace HTTP method.');
        }
        return $this->decode_response($curl, $raw);
    }

    private function new_curl(bool $json): \curl {
        $curl = new \curl();
        $headers = [
            'Authorization: Bearer ' . $this->apikey,
            'Accept: application/json',
        ];
        if ($json) {
            $headers[] = 'Content-Type: application/json';
        }
        $curl->setHeader($headers);
        return $curl;
    }

    private function decode_response(\curl $curl, $raw): array {
        $info = $curl->get_info();
        $code = (int)($info['http_code'] ?? 0);
        $decoded = is_string($raw) ? json_decode($raw, true) : null;
        if ($code < 200 || $code >= 300) {
            $message = is_array($decoded)
                ? (self::find_scalar($decoded, ['message', 'error', 'errorMessage', 'statusDescription']) ?: '')
                : '';
            throw new \moodle_exception('docspacehttpdetail', 'mod_worksheetgrader', '', (object)[
                'code' => $code ?: '0',
                'message' => clean_param((string)$message, PARAM_TEXT),
            ]);
        }
        if (!is_array($decoded)) {
            throw new \moodle_exception('docspaceinvalidresponse', 'mod_worksheetgrader', '', 'JSON');
        }
        return $decoded;
    }

    /** Recursively find a scalar by any key, case-insensitively. */
    public static function find_scalar(array $data, array $keys) {
        $wanted = array_map('strtolower', $keys);
        foreach ($data as $key => $value) {
            if (in_array(strtolower((string)$key), $wanted, true) && is_scalar($value)) {
                return $value;
            }
        }
        foreach ($data as $value) {
            if (is_array($value)) {
                $found = self::find_scalar($value, $keys);
                if ($found !== null) {
                    return $found;
                }
            }
        }
        return null;
    }

    private static function find_token_like(array $data): ?string {
        foreach ($data as $key => $value) {
            if (is_string($value) && preg_match('/token/i', (string)$key) && strlen($value) >= 16) {
                return $value;
            }
            if (is_array($value)) {
                $found = self::find_token_like($value);
                if ($found) {
                    return $found;
                }
            }
        }
        return null;
    }
}
