<?php
require('../../config.php');
require_login();\local_worksheetlibrary\service\access_service::require_view();
$sys=context_system::instance();
$PAGE->set_context($sys);$PAGE->set_url('/local/worksheetlibrary/index.php');$PAGE->set_title(get_string('library','local_worksheetlibrary'));$PAGE->set_heading(get_string('library','local_worksheetlibrary'));$PAGE->requires->css('/local/worksheetlibrary/styles.css');$PAGE->requires->js_call_amd('local_worksheetlibrary/browser','init');
$folderid=optional_param('folderid',0,PARAM_INT);$q=optional_param('q','',PARAM_TEXT);$can=
\local_worksheetlibrary\service\access_service::can_author();
if(optional_param('action','',PARAM_ALPHA)!=='' && confirm_sesskey()){\local_worksheetlibrary\service\access_service::require_author();$action=required_param('action',PARAM_ALPHA);if($action==='folder'){\local_worksheetlibrary\service\folder_service::create($folderid,required_param('name',PARAM_TEXT),$USER->id);}if($action==='item'){\local_worksheetlibrary\service\version_service::create_item($folderid,required_param('name',PARAM_TEXT),required_param('kind',PARAM_ALPHA),$USER->id);}if($action==='publish'){\local_worksheetlibrary\service\version_service::publish(required_param('versionid',PARAM_INT),$USER->id);}redirect(new moodle_url('/local/worksheetlibrary/index.php',['folderid'=>$folderid]));}
$folders=\local_worksheetlibrary\service\folder_service::tree();$params=['folderid'=>$folderid];$where='i.folderid=:folderid AND i.archived=0';if($q!==''){$where.=' AND '.$DB->sql_like('i.name',':q',false,false);$params['q']='%'.$DB->sql_like_escape($q).'%';}$items=$DB->get_records_sql("SELECT i.*,v.versionno,v.state,v.filename FROM {wslib_item} i LEFT JOIN {wslib_version} v ON v.id=i.currentversionid WHERE $where ORDER BY i.name",$params);
echo $OUTPUT->header();echo html_writer::start_div('wslib-page');echo html_writer::start_div('wslib-header');echo $OUTPUT->heading(get_string('library','local_worksheetlibrary'),2);echo html_writer::div('Một kho dùng chung cho mọi khóa học · phiên bản bất biến · Moodle File API','text-muted');echo html_writer::end_div();echo html_writer::start_div('wslib-grid');
echo html_writer::start_tag('aside',['class'=>'wslib-folders']);echo html_writer::tag('h3',get_string('folders','local_worksheetlibrary'));echo html_writer::link(new moodle_url('/local/worksheetlibrary/index.php'),'<strong>Kho phiếu</strong>');foreach($folders as $f){$label=str_repeat('&nbsp;&nbsp;',min(6,$f->depth)).'📁 '.s($f->name);echo html_writer::div(html_writer::link(new moodle_url('/local/worksheetlibrary/index.php',['folderid'=>$f->id]),$label),$f->id==$folderid?'is-active':'');}if($can){echo '<hr><form method="post"><input type="hidden" name="sesskey" value="'.sesskey().'"><input type="hidden" name="folderid" value="'.$folderid.'"><input type="hidden" name="action" value="folder"><input class="form-control mb-2" name="name" placeholder="Tên thư mục"><button class="btn btn-outline-primary btn-sm">'.get_string('newfolder','local_worksheetlibrary').'</button></form>';if($folderid){$opts=[0=>'Kho phiếu (gốc)'];foreach($folders as $fo)if((int)$fo->id!==$folderid)$opts[$fo->id]=str_repeat('— ',min(5,$fo->depth)).$fo->name;echo '<details class="mt-3"><summary>Quản lý thư mục này</summary><form method="post" action="manage.php" class="mt-2"><input type="hidden" name="sesskey" value="'.sesskey().'"><input type="hidden" name="action" value="copyfolder"><input type="hidden" name="folderid" value="'.$folderid.'"><input type="hidden" name="return" value="index">'.html_writer::select($opts,'targetfolderid',0,false,['class'=>'form-select mb-1']).'<button class="btn btn-outline-primary btn-sm w-100">Sao chép cả thư mục</button></form><form method="post" action="manage.php" class="mt-2"><input type="hidden" name="sesskey" value="'.sesskey().'"><input type="hidden" name="action" value="movefolder"><input type="hidden" name="folderid" value="'.$folderid.'"><input type="hidden" name="return" value="index">'.html_writer::select($opts,'targetfolderid',0,false,['class'=>'form-select mb-1']).'<button class="btn btn-outline-secondary btn-sm w-100">Di chuyển cả thư mục</button></form></details>';}}echo html_writer::end_tag('aside');
echo html_writer::start_tag('main',['class'=>'wslib-results']);echo '<form class="wslib-search"><input type="hidden" name="folderid" value="'.$folderid.'"><input class="form-control" name="q" value="'.s($q).'" placeholder="'.get_string('search','local_worksheetlibrary').'"></form>';if($can){echo '<div class="wslib-toolbar"><button class="btn btn-primary" data-action="new-item">+ '.get_string('newworksheet','local_worksheetlibrary').'</button></div><form class="wslib-newitem d-none" method="post" data-region="new-item-form"><input type="hidden" name="sesskey" value="'.sesskey().'"><input type="hidden" name="folderid" value="'.$folderid.'"><input type="hidden" name="action" value="item"><input class="form-control" name="name" required placeholder="Tên phiếu"><select class="form-select" name="kind"><option value="html">HTML</option><option value="office">ONLYOFFICE</option><option value="pdf">PDF</option><option value="native">Native DIGIERA</option></select><button class="btn btn-success">Tạo</button></form>';}echo html_writer::start_div('wslib-list');foreach($items as $i){$meta=strtoupper($i->kind).($i->currentversionid?' · v'.$i->versionno:' · Chưa xuất bản');echo '<button class="wslib-row" type="button" data-item="'.(int)$i->id.'" data-name="'.s($i->name).'" data-kind="'.s($i->kind).'" data-version="'.(int)$i->currentversionid.'"><span class="wslib-icon">'.($i->kind==='office'?'W':($i->kind==='pdf'?'PDF':($i->kind==='native'?'N':'H'))).'</span><span><strong>'.s($i->name).'</strong><small>'.$meta.'</small></span><span>›</span></button>'; }if(!$items)echo $OUTPUT->notification('Chưa có phiếu trong thư mục này.','info');echo html_writer::end_div();echo html_writer::end_tag('main');
echo html_writer::start_tag('aside',['class'=>'wslib-detail','data-region'=>'detail']);echo html_writer::tag('h3',get_string('details','local_worksheetlibrary'));echo html_writer::div('Chọn một phiếu để xem phiên bản, nơi sử dụng và thao tác.','text-muted', ['data-region'=>'detail-empty']);echo html_writer::div('', '', ['data-region'=>'detail-body']);echo html_writer::end_tag('aside');echo html_writer::end_div();echo html_writer::end_div();echo $OUTPUT->footer();
