<?php
require('../../config.php');require_login();require_sesskey();\local_worksheetlibrary\service\access_service::require_author();$action=required_param('action',PARAM_ALPHA);$return=optional_param('return','index',PARAM_ALPHA);$itemid=optional_param('itemid',0,PARAM_INT);$folderid=optional_param('folderid',0,PARAM_INT);$targetfolderid=optional_param('targetfolderid',0,PARAM_INT);
try{switch($action){
 case 'publish':\local_worksheetlibrary\service\version_service::publish(required_param('versionid',PARAM_INT),(int)$USER->id);break;
 case 'newdraft':\local_worksheetlibrary\service\version_service::draft($itemid,(int)$USER->id);break;
 case 'copyitem':$itemid=\local_worksheetlibrary\service\version_service::copy_item($itemid,$targetfolderid,(int)$USER->id);break;
 case 'moveitem':\local_worksheetlibrary\service\version_service::move_item($itemid,$targetfolderid);break;
 case 'copyfolder':\local_worksheetlibrary\service\folder_service::copy_tree($folderid,$targetfolderid,(int)$USER->id);break;
 case 'movefolder':\local_worksheetlibrary\service\folder_service::move($folderid,$targetfolderid);break;
 case 'bind':$courseid=required_param('courseid',PARAM_INT);if(!has_capability('moodle/course:update',context_course::instance($courseid)))throw new required_capability_exception(context_course::instance($courseid),'moodle/course:update','nopermissions','');\local_worksheetlibrary\service\binding_service::bind($itemid,$courseid,optional_param('sectionid',0,PARAM_INT));break;
 case 'savehtml':$versionid=required_param('versionid',PARAM_INT);$v=$DB->get_record('wslib_version',['id'=>$versionid,'state'=>'draft'],'*',MUST_EXIST);$html=required_param('contenthtml',PARAM_RAW);$DB->update_record('wslib_version',(object)['id'=>$versionid,'contenthtml'=>$html,'contenthash'=>hash('sha256',$html)]);break;
 case 'upload':$versionid=required_param('versionid',PARAM_INT);$v=$DB->get_record('wslib_version',['id'=>$versionid,'state'=>'draft'],'*',MUST_EXIST);if(empty($_FILES['contentfile'])||(int)$_FILES['contentfile']['error']!==UPLOAD_ERR_OK)throw new moodle_exception('Upload failed');$item=$DB->get_record('wslib_item',['id'=>$v->itemid],'*',MUST_EXIST);$filename=clean_param($_FILES['contentfile']['name'],PARAM_FILE);$ext=strtolower(pathinfo($filename,PATHINFO_EXTENSION));$allowed=$item->kind==='pdf'?['pdf']:['docx','xlsx','pptx'];if(!in_array($ext,$allowed,true))throw new moodle_exception('Unsupported file type');$file=\local_worksheetlibrary\service\file_service::store_path($versionid,$_FILES['contentfile']['tmp_name'],$filename,(string)($_FILES['contentfile']['type']??''));$DB->update_record('wslib_version',(object)['id'=>$versionid,'filename'=>$file->get_filename(),'mimetype'=>$file->get_mimetype(),'contenthash'=>$file->get_contenthash()]);break;
 default:throw new invalid_parameter_exception('Unknown action');
 }}catch(Throwable $e){redirect(new moodle_url('/local/worksheetlibrary/'.($return==='detail'?'detail.php':'index.php'),$return==='detail'?['itemid'=>$itemid]:['folderid'=>$folderid]),$e->getMessage(),0,\core\output\notification::NOTIFY_ERROR);}
redirect(new moodle_url('/local/worksheetlibrary/'.($return==='detail'?'detail.php':'index.php'),$return==='detail'?['itemid'=>$itemid]:['folderid'=>$folderid]));
