<?php
defined('MOODLE_INTERNAL') || die();
class restore_worksheetgrader_activity_structure_step extends restore_activity_structure_step {
 protected function define_structure(): array {
  $paths=[new restore_path_element('worksheetgrader','/activity/worksheetgrader'),new restore_path_element('wsg_session','/activity/worksheetgrader/sessions/session')];
  if($this->get_setting_value('userinfo')){$paths[]=new restore_path_element('wsg_team','/activity/worksheetgrader/sessions/session/teams/team');$paths[]=new restore_path_element('wsg_member','/activity/worksheetgrader/sessions/session/teams/team/members/member');$paths[]=new restore_path_element('wsg_attempt','/activity/worksheetgrader/sessions/session/teams/team/attempts/attempt');$paths[]=new restore_path_element('wsg_grade','/activity/worksheetgrader/sessions/session/teams/team/attempts/attempt/grades/grade');}
  return $this->prepare_activity_structure($paths);
 }
 protected function process_worksheetgrader($data): void {global $DB;$data=(object)$data;$oldid=$data->id;$data->course=$this->get_courseid();$data->timecreated=$this->apply_date_offset($data->timecreated);$data->timemodified=$this->apply_date_offset($data->timemodified);$newid=$DB->insert_record('worksheetgrader',$data);$this->apply_activity_instance($newid);$this->set_mapping('worksheetgrader',$oldid,$newid,true);}
 protected function process_wsg_session($data): void {global $DB;$data=(object)$data;$oldid=$data->id;$data->worksheetgraderid=$this->get_new_parentid('worksheetgrader');foreach(['sessiondate','timeopen','timeclose','timecreated','timemodified'] as $f)$data->$f=$this->apply_date_offset($data->$f);$data->libraryitemid=0;$data->libraryversionid=0;$data->migrationstatus=($data->worksheetkind??'html')==='office'?'not_required':($data->migrationstatus??'not_required');$newid=$DB->insert_record('wsg_session',$data);$this->set_mapping('wsg_session',$oldid,$newid,true);}
 protected function process_wsg_team($data): void {global $DB;$data=(object)$data;$oldid=$data->id;$data->sessionid=$this->get_new_parentid('wsg_session');$data->representativeuserid=$this->get_mappingid('user',$data->representativeuserid,0);$newid=$DB->insert_record('wsg_team',$data);$this->set_mapping('wsg_team',$oldid,$newid,true);}
 protected function process_wsg_member($data): void {global $DB;$data=(object)$data;$data->teamid=$this->get_new_parentid('wsg_team');$data->userid=$this->get_mappingid('user',$data->userid,0);$data->addedby=$this->get_mappingid('user',$data->addedby,0);if($data->userid)$DB->insert_record('wsg_member',$data);}
 protected function process_wsg_attempt($data): void {global $DB;$data=(object)$data;$oldid=$data->id;$data->teamid=$this->get_new_parentid('wsg_team');$data->sessionid=$this->get_new_parentid('wsg_session');$data->submitteruserid=$this->get_mappingid('user',$data->submitteruserid,0);$data->gradedby=$this->get_mappingid('user',$data->gradedby,0);$members=json_decode((string)($data->membersnapshot??'[]'),true);if(is_array($members)){$mapped=[];foreach($members as $uid){$new=$this->get_mappingid('user',(int)$uid,0);if($new)$mapped[]=$new;}$data->membersnapshot=json_encode(array_values(array_unique($mapped)));}foreach(['timestarted','timemodified','timesubmitted','timegraded'] as $f)$data->$f=$this->apply_date_offset($data->$f);$newid=$DB->insert_record('wsg_attempt',$data);$this->set_mapping('wsg_attempt',$oldid,$newid,true);}
 protected function process_wsg_grade($data): void {global $DB;$data=(object)$data;$data->attemptid=$this->get_new_parentid('wsg_attempt');$data->userid=$this->get_mappingid('user',$data->userid,0);$data->publishedby=$this->get_mappingid('user',$data->publishedby,0);if($data->userid)$DB->insert_record('wsg_grade',$data);}
 protected function after_execute(): void {$this->add_related_files('mod_worksheetgrader','source','wsg_session');$this->add_related_files('mod_worksheetgrader','docspacetemplate','wsg_session');$this->add_related_files('mod_worksheetgrader','officetemplate','wsg_session');if($this->get_setting_value('userinfo')){$this->add_related_files('mod_worksheetgrader','attemptimage','wsg_attempt');$this->add_related_files('mod_worksheetgrader','docspacesnapshot','wsg_attempt');$this->add_related_files('mod_worksheetgrader','officesubmission','wsg_attempt');}}
}
