<?php
require('../../config.php');require_once(__DIR__.'/locallib.php');
$id=required_param('id',PARAM_INT);$sessionid=required_param('sessionid',PARAM_INT);[$cm,$course,$activity,$context]=worksheetgrader_get_page_context($id);require_capability('mod/worksheetgrader:managesessions',$context);if(!\mod_worksheetgrader\service\v12_gate::enabled_for_course((int)$course->id))redirect(new moodle_url('/mod/worksheetgrader/sessions.php',['id'=>$id]));$session=$DB->get_record('wsg_session',['id'=>$sessionid,'worksheetgraderid'=>$activity->id],'*',MUST_EXIST);worksheetgrader_setup_page($PAGE,$cm,$course,$activity,get_string('readyopen','mod_worksheetgrader'),'ready.php',['sessionid'=>$sessionid]);$error='';
if(data_submitted()&&confirm_sesskey()){
 try{\mod_worksheetgrader\service\readiness_service::open($session,$activity,$context,(int)$USER->id);worksheetgrader_redirect(new moodle_url('/mod/worksheetgrader/view.php',['id'=>$id]),'Buổi đã mở. Học sinh có thể bắt đầu làm bài.');}catch(Throwable $e){$error=$e->getMessage();$session=$DB->get_record('wsg_session',['id'=>$sessionid],'*',MUST_EXIST);}
}
$result=\mod_worksheetgrader\service\readiness_service::inspect($session,$activity,$context);$teamcount=($session->teammode==='individual')?$result['studentcount']:$DB->count_records('wsg_team',['sessionid'=>$sessionid]);$submitted=$DB->count_records_select('wsg_attempt','sessionid=? AND status IN (?,?)',[$sessionid,'submitted','graded']);
echo $OUTPUT->header();echo html_writer::div('<span class="wsg-v12-eyebrow">BƯỚC 4/4</span><h2>Xác nhận và mở buổi học</h2><p>Kiểm tra toàn bộ cấu hình trước khi học sinh truy cập.</p>','wsg-v12-pagehead');echo $OUTPUT->render(worksheetgrader_nav_tabs($cm,'sessions',$sessionid));
if($error!=='')echo $OUTPUT->notification(s($error),'error');echo '<div class="wsg-v12-steps"><div class="wsg-v12-step is-done"><span>✓</span><strong>Thông tin buổi</strong></div><div class="wsg-v12-step is-done"><span>✓</span><strong>Chọn phiếu</strong></div><div class="wsg-v12-step is-done"><span>✓</span><strong>'.($session->teammode==='individual'?'Cá nhân':'Tạo nhóm').'</strong></div><div class="wsg-v12-step is-active"><span>4</span><strong>Xác nhận & mở</strong></div></div>';
echo '<div class="wsg-ready-layout"><main><div class="wsg-ready-summary card"><div class="card-body"><div class="wsg-ready-title"><div><span class="badge bg-light text-primary">'.s(strtoupper($session->worksheetkind??'html')).'</span><h3>'.s($session->name).'</h3><p>'.userdate($session->sessiondate).'</p></div><span class="wsg-ready-score '.($result['ok']?'is-ok':'is-warn').'">'.($result['ok']?'Sẵn sàng':'Cần xử lý').'</span></div><div class="wsg-ready-stats"><div><strong>'.$result['studentcount'].'</strong><span>Học sinh</span></div><div><strong>'.$teamcount.'</strong><span>'.($session->teammode==='individual'?'Bài cá nhân':'Nhóm').'</span></div><div><strong>'.$submitted.'</strong><span>Đã nộp</span></div><div><strong>'.s((string)$session->maxpoints).'</strong><span>Điểm tối đa</span></div></div></div></div><div class="wsg-ready-grid">';foreach($result['checks'] as $key=>$check){echo '<div class="wsg-ready-card '.($check['ok']?'is-ok':'is-blocked').'"><span>'.($check['ok']?'✓':'!').'</span><div><strong>'.s($check['label']).'</strong><p>'.($check['ok']?'Đã đạt yêu cầu':'Cần hoàn tất trước khi mở buổi').'</p></div></div>';}echo '</div></main><aside class="wsg-ready-actions card"><div class="card-body"><h3>Trước khi mở</h3><p>Khi mở buổi, học sinh có thể bắt đầu làm bài theo thời gian đã cấu hình.</p><ul><li>Phiếu được đóng băng theo đúng phiên bản đã chọn.</li><li>Nhóm được khóa khi buổi mở.</li><li>Bài Office chỉ được ghi nhận nộp sau force-save thành công.</li></ul><form method="post"><input type="hidden" name="sesskey" value="'.sesskey().'"><button class="btn btn-primary btn-lg w-100" '.(!$result['ok']?'disabled':'').'>Mở buổi học</button></form><a class="btn btn-outline-secondary w-100 mt-2" href="'.(new moodle_url('/mod/worksheetgrader/teams.php',['id'=>$id,'sessionid'=>$sessionid]))->out().'">← Quay lại chỉnh nhóm</a></div></aside></div>';echo $OUTPUT->footer();
